### PR TITLE
#95 Add support for browser back button navigation

### LINKED ISSUE #95: The back button is usless. 😞
It has been brought to my attention by [Rosella Celina](https://profiles.wordpress.org/rosellecelina) on [WordPress.org support forum](https://wordpress.org/support/topic/back-button-doesnt-go-to-the-top-of-the-last-post) that pressing the back button on your browser does not scroll up to the previous post.

[Video](https://youtu.be/SZpIjXqkv3o) demonstrating the 🐛 

I was unaware of this bug due to the fact the plugin was designed for users not to press the back button but it should still at least scroll back to the previous post which it does only instead it scrolls to the very end of the last post with another post in view and not the beginning of the post.

Additional Javascript will be needed to support this properly so this is the checklist.

### The Checklist
- [ ] Check history state that the previous post matches before scrolling back up to the beginning of that post.
- [ ] Animate the scroll for a smooth transition within 600 milliseconds.
- [ ] If no further previous posts found then just go back as normal.

### PR DESCRIPTION
**Pull request by lex111**
Fixes #95

### CODE REVIEW

**Comment by seb86** [comment]
Hi @lex111 

Thank you for submitting your pull request. I was not expecting it so quickly. I will test it later this week and give my feedback.

Thanks again.

**Comment by seb86** [comment]
Hi @lex111 

It looks good and works well going forward again too. One piece of feedback.

Would it be possible to make the animation slower for articles that are large in height?

**Comment by lex111** [comment]
@seb86 hello, 

> Would it be possible to make the animation slower for articles that are large in height?

I do not think so, and why? How do you imagine this?

**Comment by seb86** [comment]
Hello @lex111,

> I do not think so, and why? How do you imagine this?

I imagine reading the height of the previous article and if it is equal to X height or more then the animation should be Y speed else Y speed is 1 (1000) second.

Y speed could be increased to 1.5 to 2 seconds for long articles.

The reason for this is because on long articles I find it hurts my eyes. It's too flashy and not as smooth compared to animating on smaller articles.

**Comment by lex111** [comment]
@seb86 well, write please what height you think is short and lengthy of the article. Or a formula so that I know how to calculate it.

**Comment by seb86** [comment]
@lex111 Did some further testing. Appears to be smooth if you just started reading the next post but if you are lets say half way reading the second post which is also long then it does not appear to look smooth. So may have to count previous post and the height from the position of the current post they are reading if that is possible.

So lets say for every 1000px in height of the previous post plus the current position that the animation speed is increased by another 600ms.

What do you think?

**Comment by lex111** [comment]
@seb86 It's quite difficult in my opinion, need to think... and if at all to remove the smooth scroll?

**Comment by seb86** [comment]
@lex111 If you think it is to much lets leave it for now. Thank you for your contribution.

**Comment by lex111** [comment]
@seb86 I was glad to help, I just do not know how to do it, but it makes sense.

**Pull request merged**
